### ISSUE TITLE
build fast compile failed

### ISSUE THREAD

**Issue by anakin** [Achain-Dev/Achain_linux#9]
OS:ubuntu

[ 19%] Building CXX object CMakeFiles/fc.dir/src/thread/thread.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/fc.dir/build.make:182: recipe for target 'CMakeFiles/fc.dir/src/thread/thread.cpp.o' failed
make[2]: *** [CMakeFiles/fc.dir/src/thread/thread.cpp.o] Error 4
CMakeFiles/Makefile2:263: recipe for target 'CMakeFiles/fc.dir/all' failed
make[1]: *** [CMakeFiles/fc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by willchain** [comment]
thanks for your feedback. pls follow the instructions linux_installation guide or build_ubuntu.sh script.
make sure your have installed the dependent packages.

**Comment by seaify** [comment]
same problem, ubuntu

**Comment by willchain** [comment]
what's your os version and gcc version ?

**Comment by seaify** [comment]
@WillAchain it's working now, problem is ubuntu default install 1.6.2 bootstrap, i have manually install 1.5.9, so it works, thanks
